#
# Descriptive metadata
#

# url without trailing slash

url:            http://sitigrema.cz

language:       cs
analytics:      UA-60568686-1
name:           Grema
title:          Zakázkové šití Grema
description:    Výroba chovatelských potřeb a zakázkové šití pro koně, pejsky a další zvířecí miláčky.
keywords:
    - koně
    - šití
    - chovatelské potřeby
    - popruhy
    - otěže
    - vodítko

contact:
    name:       Grema
    email:      chovatelskepotrebygrema@seznam.cz
    phone:      +420 725 666 161
    facebook:   https://www.facebook.com/chovateskepotrebyGrema

author:
    name:       imm studios, z.s.
    email:      martas@imm.cz
    url:        http://imm.cz
    facebook:   https://www.facebook.com/immstudios
    twitter:    https://twitter.com/immstudios

#
# Build options
#

# Additional CSS
css:
    - /static/css/style.css

js:
    - /static/js/social.js

favicons_path:  /static/img/favicons
theme_color:    AB6431

include:        ["robots.txt"]
exclude:        ["_doc", "LICENSE", "README.md", "_sources", "build.py"]
markdown:       kramdown
sass:
    sass_dir:   _sass
    style:      compressed
