#
# Descriptive metadata
#

# url without trailing slash

url:            http://sitigrema.cz

name:           Grema
title:          Zakázkové šití Grema
description:    Výroba chovatelských potřeb a zakázkové šití pro koně, pejsky a další zvířecí miláčky.
keywords:       koně, šití, chovatelské potřeby, nylonové popruhy, otěže, uzdečka, podbřišník, vodítko
language:       cs
analytics:      UA-60568686-1

contact:
    name:       Grema
    email:      chovatelskepotrebygrema@seznam.cz
    phone:      +420 775 696 902
    facebook:   https://www.facebook.com/chovateskepotrebyGrema

author:
    name:       imm studios, z.s.
    email:      produkce@imm.cz
    url:        http://imm.cz
    facebook:   https://www.facebook.com/immstudios
    twitter:    https://twitter.com/immstudios

#
# Build options
#


# Additional CSS
css:
                - //maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
                - http://fonts.googleapis.com/css?family=Lobster


include:        ["robots.txt"]
exclude:        ["_doc", "LICENSE", "README.md"]
markdown:       redcarpet
sass:
    sass_dir:   _sass
    style:      compressed
