#
# Descriptive metadata
#

url:            https://sitigrema.cz

language:       cs
analytics:      UA-60568686-1
name:           Grema
title:          Šití Grema
description:    Výroba chovatelských potřeb a zakázkové šití pro koně, pejsky a další zvířecí miláčky.
keywords:
    - šití
    - chovatelské potřeby
    - popruh
    - otěže
    - vodítko

contact:
    name:       Grema
    email:      chovatelskepotrebygrema@seznam.cz
    phone:      +420 725 666 161
    facebook:   https://www.facebook.com/chovateskepotrebyGrema

author:
    name:       imm studios, z.s.
    email:      martas@imm.cz
    url:        https://imm.cz
    facebook:   https://www.facebook.com/immstudios
    twitter:    https://twitter.com/immstudios
    github:     https://github.com/immstudios

#
# Build options
#

css:
    - https://fonts.googleapis.com/css?family=Lobster
    - https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700&subset=latin,latin-ext
    - /static/css/font-awesome.min.css
    - /static/css/style.css

js:
    - /static/js/social.js

image:          /static/img/cover1.jpg
favicons_path:  /static/img/favicons
theme_color:    AB6431

include:        ["robots.txt"]
exclude:        ["_doc", "LICENSE", "README.md", "_sources", "build.py"]
markdown:       kramdown
sass:
    sass_dir:   _sass
    style:      compressed
