- id    : 0
  title : Koníci
  slug  : konici
  groups :
    - id    : 1
      title : Barevné sady
      slug  : barevne-sady
      has_index: 1

    - id    : 2
      title : Beránci, obaly a potahy
      slug  : beranci-obaly-a-potahy
      products :
        - id   : 2000
          title: Obal na anglické sedlo
          slug : obal-na-anglicke-sedlo
        - id   : 2001
          title: Obal na drezurní sedlo
          slug : obal-na-drezurni-sedlo
        - id   : 2002
          title: Obal na třmeny
          slug : obal-na-trmeny
        - id   : 2003
          title: Obal na westernové sedlo
          slug : obal-na-westernove-sedlo
        - id   : 2004
          title: Potah na podbřišník
          slug : potah-na-podbrisnik
        - id   : 2005
          title: Potah na posedlí
          slug : potah-na-posedli
        - id   : 2006
          title: Potah na uzdečku či ohlávku
          slug : potah-na-uzdecku-ci-ohlavku

    - id    : 4
      title : Deky a bederní deky na koně
      slug  : deky-a-bederni-deky-na-kone
      products :
        - id   : 4000
          title: Bederní deka fleesová
          slug : bederni-deka-fleesova
        - id   : 4001
          title: Bederní deka nepromokavá
          slug : bederni-deka-nepromokava
        - id   : 4002
          title: Deka fleesová - odpocovací
          slug : deka-fleesova-odpocovaci
        - id   : 4003
          title: Deka nepromokavá
          slug : deka-nepromokava
        - id   : 4004
          title: Deka softshell
          slug : deka-softshell
        - id   : 4005
          title: Deka stájová
          slug : deka-stajova

    - id    : 5
      title : Lonžovací potřeby
      slug  : lonzovaci-potreby
      products :
        - id   : 5000
          title: Chambon
          slug : chambon
        - id   : 5001
          title: Lonže a dvojité lonže
          slug : lonze-a-dvojite-lonze
        - id   : 5002
          title: Lonžovací spojka
          slug : lonzovaci-spojka
        - id   : 5003
          title: Lonžovací obnosek nylonový
          slug : lonzovaci-obnosek-nylonovy
        - id   : 5004
          title: Lonžovací obřišníky
          slug : lonzovaci-obrisniky
        - id   : 5005
          title: Vyvazovací otěže s gumou
          slug : vyvazovaci-oteze-s-gumou
        - id   : 5006
          title: Vyvazovací otěže pevné
          slug : vyvazovaci-oteze-pevne

    - id    : 6
      title : Martingaly, poprsáky a příslušenství
      slug  : martingaly-poprsaky-a-prislusenstvi
      products :
        - id   : 6000
          title: Martingal anglický
          slug : martingal-anglicky
        - id   : 6001
          title: Martingal westernový
          slug : martingal-westernovy
        - id   : 6002
          title: Martingalová vidlice k poprsáku
          slug : martingalova-vidlice-k-poprsaku
        - id   : 6003
          title: Očko k podbřišníku
          slug : ocko-k-podbrisniku
        - id   : 6004
          title: Poprsák anglický
          slug : poprsak-anglicky
        - id   : 6005
          title: Poprsák dostihový
          slug : poprsak-dostihovy
        - id   : 6006
          title: Poprsák westernový
          slug : poprsak-westernovy

    - id    : 7
      title : Ohlávky, vodítka a čabraky
      slug  : ohlavky-voditka-a-cabraky
      products :
        - id   : 7000
          title: Ohlávka
          slug : ohlavka
        - id   : 7001
          title: Ohlávka podložená
          slug : ohlavka-podlozena
        - id   : 7002
          title: Ohlávka s beránkem
          slug : ohlavka-s-berankem
        - id   : 7003
          title: Ohlávka Dually Halter
          slug : ohlavka-dually-halter
        - id   : 7004
          title: Ohlávka provazová
          slug : ohlavka-provazova
        - id   : 7005
          title: Vodítka plochá
          slug : voditka-plocha
        - id   : 7006
          title: Vodítka lanová
          slug : voditka-lanova
        - id   : 7007
          title: Vodítka s řetízkem
          slug : voditka-s-retizkem
        - id   : 7008
          title: Čabraky látkové
          slug : cabraky-latkove
        - id   : 7009
          title: Čabraky háčkované a pletené
          slug : cabraky-hackovane-a-pletene

    - id    : 8
      title : Ochrana nohou a reflexní prvky
      slug  : ochrana-nohou-a-reflexni-prvky
      products :
        - id   : 8000
          title: Fleesové bandáže
          slug : fleesove-bandaze
        - id   : 8001
          title: Reflexní bandáže
          slug : reflexni-bandaze
        - id   : 8002
          title: Reflexní pásky pro jezdce
          slug : reflexni-pasky-pro-jezdce
        - id   : 8003
          title: Reflexní pásky pro koně
          slug : reflexni-pasky-pro-kone
        - id   : 8004
          title: Podložky pod bandáže
          slug : podlozky-pod-bandaze
        - id   : 8005
          title: Transportní kamaše
          slug : transportni-kamase
        - id   : 8006
          title: Chrániče neoprenové
          slug : chranice-neoprenove
        - id   : 8007
          title: Chrániče kloubkové
          slug : chranice-kloubkove
        - id   : 8008
          title: Zvlhčovací zvony
          slug : zvlhcovaci-zvony

    - id    : 9
      title : Otěže a pomocné otěže
      slug  : oteze-a-pomocne-oteze
      products :
        - id   : 9000
          title: Otěže ploché
          slug : oteze-ploche
        - id   : 9001
          title: Otěže lanové
          slug : oteze-lanove
        - id   : 9002
          title: Otěže protiskluzové
          slug : oteze-protiskluzove
        - id   : 9003
          title: Jednokarabinové otěže
          slug : jednokarabinove-oteze
        - id   : 9004
          title: Průvlečky
          slug : pruvlecky

    - id    : 10
      title : Podbřišníky a podocasníky
      slug  : podbrisniky-a-podocasniky
      products :
        - id   : 10000
          title: Podbřišník anglický
          slug : podbrisnik-anglicky
        - id   : 10001
          title: Podbřišník drezurní
          slug : podbrisnik-drezurni
        - id   : 10002
          title: Podbřišník westernový
          slug : podbrisnik-westernovy
        - id   : 10003
          title: Podocasník
          slug : podocasnik

    - id    : 11
      title : Podsedlové a jiné dečky
      slug  : podsedlove-a-jine-decky
      products :
        - id   : 11000
          title: Dečka obdélníková
          slug : decka-obdelnikova
        - id   : 11001
          title: Dečka drezurní
          slug : decka-drezurni
        - id   : 11002
          title: Dečka pod lonžovací obřišník
          slug : decka-pod-lonzovaci-obrisnik
        - id   : 11003
          title: Dečka s cípem
          slug : decka-s-cipem
        - id   : 11004
          title: Dečka vykrojená
          slug : decka-vykrojena
        - id   : 11005
          title: Dečka westernová
          slug : decka-westernova
        - id   : 11006
          title: Podsedlová dečka dostihová
          slug : podsedlova-decka-dostihova
        - id   : 11007
          title: Podsedlová dečka barokní
          slug : podsedlova-decka-barokni

    - id    : 12
      title : Třmeny a třmenové řemeny
      slug  : trmeny-a-trmenove-remeny
      products :
        - id   : 12000
          title: Třmeny barevné
          slug : trmeny-barevne
        - id   : 12001
          title: Třmenové řemeny klasické
          slug : trmenove-remeny-klasicke
        - id   : 12002
          title: Třmenové řemeny jednořemenné
          slug : trmenove-remeny-jednoremenne

    - id    : 13
      title : Uzdečky a bezudidlovky
      slug  : uzdecky-a-bezudidlovky
      products :
        - id   : 13000
          title: Bezudidlová uzdečka
          slug : bezudidlova-uzdecka
        - id   : 13001
          title: Bezudidlová uzdečka Bitless Bridle
          slug : bezudidlova-uzdecka-bitless-bridle
        - id   : 13002
          title: Bezudidlová uzdečka Sidepull
          slug : bezudidlova-uzdecka-sidepull
        - id   : 13003
          title: Uzdečka anglická
          slug : uzdecka-anglicka
        - id   : 13004
          title: Uzdečka bez nánosníku
          slug : uzdecka-bez-nanosniku
        - id   : 13005
          title: Uzdečka dvouuška
          slug : uzdecka-dvouuska
        - id   : 13006
          title: Uzdečka jednouška
          slug : uzdecka-jednouska
        - id   : 13007
          title: Uzdečka jednořemínková
          slug : uzdecka-jednoreminkova
        - id   : 13008
          title: Uzdečka jednořemínková v kombinaci s provazovou ohlávkou
          slug : uzdecka-jednoreminkova-v-kombinaci-s-provazovou-ohlavkou
        - id   : 13009
          title: Uzdečka s Hackamore
          slug : uzdecka-s-hackamore
        - id   : 13010
          title: Uzdečka 3 v 1 v kombinaci s bezudidlovkou a ohlávkou
          slug : uzdecka-3-v-1-v-kombinaci-s-bezudidlovkou-a-ohlavkou
        - id   : 13011
          title: Uzdečka v kombinaci s provazovou ohlávkou
          slug : uzdecka-v-kombinaci-s-provazovou-ohlavkou
        - id   : 13012
          title: Uzdečka westernová
          slug : uzdecka-westernova

    - id    : 14
      title : Výstavy a předvádění
      slug  : vystavy-a-predvadeni
      products :
        - id   : 14000
          title: Výstavní a předváděcí ohlávky
          slug : vystavni-a-predvadeci-ohlavky
        - id   : 14001
          title: Výstavní a předváděcí uzdečky
          slug : vystavni-a-predvadeci-uzdecky
        - id   : 14002
          title: Výstavní a předváděcí vodítka
          slug : vystavni-a-predvadeci-voditka

- id    : 1
  title : Pejsci a kočičky
  slug  : pejsci-a-kocicky
  groups :
    - id    : 1
      title : Cestování
      slug  : cestovani
      products :
        - id   : 1000
          title: Autopostroj eco
          slug : autopostroj-eco
        - id   : 1001
          title: Autopostroj komfort
          slug : autopostroj-komfort
        - id   : 1002
          title: Autovak
          slug : autovak
        - id   : 1003
          title: Brašny
          slug : brasny
        - id   : 1004
          title: Deky
          slug : deky
        - id   : 1005
          title: Mříže a sítě do auta
          slug : mrize-a-site-do-auta
        - id   : 1006
          title: Podložky a polštáře
          slug : podlozky-a-polstare
        - id   : 1007
          title: Reflexní dečka
          slug : reflexni-decka
        - id   : 1008
          title: Reflexní vesta
          slug : reflexni-vesta
        - id   : 1009
          title: Spojka k autopásu
          slug : spojka-k-autopasu

    - id    : 2
      title : Hračky
      slug  : hracky
      products :
        - id   : 2000
          title: Činka
          slug : cinka
        - id   : 2001
          title: Bobík
          slug : bobik
        - id   : 2002
          title: Bonbonek
          slug : bonbonek
        - id   : 2003
          title: Pešek
          slug : pesek
        - id   : 2004
          title: Pletené hračky
          slug : pletene-hracky
        - id   : 2005
          title: Plyšový míček
          slug : plysovy-micek
        - id   : 2006
          title: Přetahovadlo
          slug : pretahovadlo

    - id    : 3
      title : Oblečky a botičky
      slug  : oblecky-a-boticky
      has_index: 1
      products :
        - id   : 3000
          title: Botičky
          slug : boticky
        - id   : 3001
          title: Dečka flees
          slug : decka-flees
        - id   : 3002
          title: Dečka softshell
          slug : decka-softshell
        - id   : 3003
          title: Dečka zimní
          slug : decka-zimni
        - id   : 3004
          title: Hárací kalhotky
          slug : haraci-kalhotky
        - id   : 3005
          title: Pláštěnka
          slug : plastenka
        - id   : 3006
          title: Ponožky
          slug : ponozky
        - id   : 3007
          title: Protiznačkovací pás
          slug : protiznackovaci-pas
        - id   : 3008
          title: Reflexní program
          slug : reflexni-program

    - id    : 4
      title : Obojky a vodítka
      slug  : obojky-a-voditka
      products :
        - id   : 4000
          title: Obojek eko
          slug : obojek-eko
        - id   : 4001
          title: Obojek posuvný
          slug : obojek-posuvny
        - id   : 4002
          title: Obojek podložený
          slug : obojek-podlozeny
        - id   : 4003
          title: Obojek zesílený
          slug : obojek-zesileny
        - id   : 4004
          title: Stopovačka
          slug : stopovacka
        - id   : 4005
          title: Vodítka klasik
          slug : voditka-klasik
        - id   : 4006
          title: Vodítka zesílená
          slug : voditka-zesilena
        - id   : 4007
          title: Vodítka výstavní
          slug : voditka-vystavni
        - id   : 4008
          title: Vodítka pletená
          slug : voditka-pletena
        - id   : 4009
          title: Vodítko nastavitelné
          slug : voditko-nastavitelne

    - id    : 5
      title : Pelíšky a podložky
      slug  : pelisky-a-podlozky
      products :
        - id   : 5000
          title: Deka
          slug : deka
        - id   : 5001
          title: Matrace
          slug : matrace
        - id   : 5002
          title: Pelíšek eko
          slug : pelisek-eko
        - id   : 5003
          title: Pelíšek komfort
          slug : pelisek-komfort
        - id   : 5004
          title: Podložka či polštář
          slug : podlozka-ci-polstar
        - id   : 5005
          title: Potah
          slug : potah

    - id    : 6
      title : Výcvik
      slug  : vycvik
      products :
        - id   : 6000
          title: Náhubek "Popruh"
          slug : nahubek-popruh
        - id   : 6001
          title: Náhubek "Trubička"
          slug : nahubek-trubicka
        - id   : 6002
          title: Ohlávka halti s obojkem
          slug : ohlavka-halti-s-obojkem
        - id   : 6003
          title: Pamlskovníky
          slug : pamlskovniky
        - id   : 6004
          title: Výcviková ledvinka
          slug : vycvikova-ledvinka

    - id    : 7
      title : Postroje
      slug  : postroje
      products :
        - id   : 7000
          title: Dogtreking
          slug : dogtreking
        - id   : 7001
          title: Opasky a pásy pro lidi
          slug : opasky-a-pasy-pro-lidi
        - id   : 7002
          title: Postroj Active
          slug : postroj-active
        - id   : 7003
          title: Postroj Cyklo a Ski
          slug : postroj-cyklo-a-ski
        - id   : 7004
          title: Postroj Klasik
          slug : postroj-klasik
        - id   : 7005
          title: Postroj Komfort
          slug : postroj-komfort
        - id   : 7006
          title: Proti tahání Eco
          slug : proti-tahani-eco
        - id   : 7007
          title: Proti tahání Pull
          slug : proti-tahani-pull
        - id   : 7008
          title: Postroje na přání
          slug : postroje-na-prani
        - id   : 7009
          title: Postroj s brašnami
          slug : postroj-s-brasnami

- id    : 2
  title : Jiná zvířátka
  slug  : jina-zviratka
  groups :
- id    : 3
  title : Lidičky a jezdci
  slug  : lidicky-a-jezdci
  groups :
- id    : 4
  title : Bytový textil
  slug  : bytovy-textil
  groups :
    - id    : 1
      title : Ložní prádlo
      slug  : lozni-pradlo
      has_index: 1

    - id    : 2
      title : Potahy na sedačky, křesla
      slug  : potahy-na-sedacky-kresla
      has_index: 1

    - id    : 3
      title : Záclony
      slug  : zaclony
      has_index: 1

    - id    : 4
      title : Závěsy
      slug  : zavesy
      has_index: 1

    - id    : 5
      title : Ubrusy
      slug  : ubrusy
      has_index: 1

- id    : 5
  title : Potahy na autosedačky
  slug  : potahy-na-autosedacky
