- id    : 0
  title : Koníci
  slug  : konici
  groups :
    - id    : 1
      title : Barevné sady
      slug  : barevne-sady

    - id    : 2
      title : Beránci, obaly a potahy
      slug  : beranci-obaly-a-potahy
      products :
        - id   : 2000
          title: Obal na anglické sedlo
          slug : obal-na-anglicke-sedlo
        - id   : 2001
          title: Obal na drezurní sedlo
          slug : obal-na-drezurni-sedlo
        - id   : 2002
          title: Obal na třmeny
          slug : obal-na-trmeny
        - id   : 2003
          title: Obal na westernové sedlo
          slug : obal-na-westernove-sedlo
        - id   : 2004
          title: Potah na podbřišník
          slug : potah-na-podbrisnik
        - id   : 2005
          title: Potah na posedlí
          slug : potah-na-posedli
        - id   : 2006
          title: Potah na uzdečku či ohlávku
          slug : potah-na-uzdecku-ci-ohlavku

    - id    : 3
      title : Deky a bederní deky na koně
      slug  : deky-a-bederni-deky-na-kone
      products :
        - id   : 3000
          title: Bederní deka fleesová
          slug : bederni-deka-fleesova
        - id   : 3001
          title: Bederní deka nepromokavá
          slug : bederni-deka-nepromokava
        - id   : 3002
          title: Deka fleesová - odpocovací
          slug : deka-fleesova-odpocovaci
        - id   : 3003
          title: Deka nepromokavá
          slug : deka-nepromokava
        - id   : 3004
          title: Deka softshell
          slug : deka-softshell
        - id   : 3005
          title: Deka stájová
          slug : deka-stajova

    - id    : 4
      title : Lonžovací potřeby
      slug  : lonzovaci-potreby
      products :
        - id   : 4000
          title: Chambon
          slug : chambon
        - id   : 4001
          title: Lonže a dvojité lonže
          slug : lonze-a-dvojite-lonze
        - id   : 4002
          title: Lonžovací spojka
          slug : lonzovaci-spojka
        - id   : 4003
          title: Lonžovací obnosek nylonový
          slug : lonzovaci-obnosek-nylonovy
        - id   : 4004
          title: Lonžovací obřišníky
          slug : lonzovaci-obrisniky
        - id   : 4005
          title: Vyvazovací otěže s gumou
          slug : vyvazovaci-oteze-s-gumou
        - id   : 4006
          title: Vyvazovací otěže pevné
          slug : vyvazovaci-oteze-pevne

    - id    : 5
      title : Martingaly, poprsáky a příslušenství
      slug  : martingaly-poprsaky-a-prislusenstvi
      products :
        - id   : 5000
          title: Martingal anglický
          slug : martingal-anglicky
        - id   : 5001
          title: Martingal westernový
          slug : martingal-westernovy
        - id   : 5002
          title: Martingalová vidlice k poprsáku
          slug : martingalova-vidlice-k-poprsaku
        - id   : 5003
          title: Očko k podbřišníku
          slug : ocko-k-podbrisniku
        - id   : 5004
          title: Poprsák anglický
          slug : poprsak-anglicky
        - id   : 5005
          title: Poprsák dostihový
          slug : poprsak-dostihovy
        - id   : 5006
          title: Poprsák westernový
          slug : poprsak-westernovy

    - id    : 6
      title : Ohlávky, vodítka a čabraky
      slug  : ohlavky-voditka-a-cabraky
      products :
        - id   : 6000
          title: Ohlávka
          slug : ohlavka
        - id   : 6001
          title: Ohlávka podložená
          slug : ohlavka-podlozena
        - id   : 6002
          title: Ohlávka s beránkem
          slug : ohlavka-s-berankem
        - id   : 6003
          title: Ohlávka Dually Halter
          slug : ohlavka-dually-halter
        - id   : 6004
          title: Vodítka plochá
          slug : voditka-plocha
        - id   : 6005
          title: Vodítka lanová
          slug : voditka-lanova
        - id   : 6006
          title: Vodítka s řetízkem
          slug : voditka-s-retizkem
        - id   : 6007
          title: Čabraky látkové
          slug : cabraky-latkove
        - id   : 6008
          title: Čabraky háčkované a pletené
          slug : cabraky-hackovane-a-pletene

    - id    : 7
      title : Ochrana nohou a reflexní prvky
      slug  : ochrana-nohou-a-reflexni-prvky
      products :
        - id   : 7000
          title: Fleesové bandáže
          slug : fleesove-bandaze
        - id   : 7001
          title: Reflexní bandáže
          slug : reflexni-bandaze
        - id   : 7002
          title: Reflexní pásky pro jezdce
          slug : reflexni-pasky-pro-jezdce
        - id   : 7003
          title: Reflexní pásky pro koně
          slug : reflexni-pasky-pro-kone
        - id   : 7004
          title: Podložky pod bandáže
          slug : podlozky-pod-bandaze
        - id   : 7005
          title: Transportní kamaše
          slug : transportni-kamase
        - id   : 7006
          title: Chrániče neoprenové
          slug : chranice-neoprenove
        - id   : 7007
          title: Chrániče kloubkové
          slug : chranice-kloubkove

    - id    : 8
      title : Otěže a pomocné otěže
      slug  : oteze-a-pomocne-oteze
      products :
        - id   : 8000
          title: Otěže ploché
          slug : oteze-ploche
        - id   : 8001
          title: Otěže lanové
          slug : oteze-lanove
        - id   : 8002
          title: Otěže protiskluzové
          slug : oteze-protiskluzove
        - id   : 8003
          title: Průvlečky
          slug : pruvlecky

    - id    : 9
      title : Podbřišníky
      slug  : podbrisniky
      products :
        - id   : 9000
          title: Podbřišník anglický
          slug : podbrisnik-anglicky
        - id   : 9001
          title: Podbřišník drezurní
          slug : podbrisnik-drezurni
        - id   : 9002
          title: Podbřišník westernový
          slug : podbrisnik-westernovy

    - id    : 10
      title : Podsedlové a jiné dečky
      slug  : podsedlove-a-jine-decky
      products :
        - id   : 10000
          title: Dečka obdélníková
          slug : decka-obdelnikova
        - id   : 10001
          title: Dečka drezurní
          slug : decka-drezurni
        - id   : 10002
          title: Dečka pod lonžovací obřišník
          slug : decka-pod-lonzovaci-obrisnik
        - id   : 10003
          title: Dečka s cípem
          slug : decka-s-cipem
        - id   : 10004
          title: Dečka vykrojená
          slug : decka-vykrojena
        - id   : 10005
          title: Dečka westernová
          slug : decka-westernova
        - id   : 10006
          title: Podsedlová dečka dostihová
          slug : podsedlova-decka-dostihova
        - id   : 10007
          title: Podsedlová dečka barokní
          slug : podsedlova-decka-barokni

    - id    : 11
      title : Třmenové řemeny
      slug  : trmenove-remeny
      products :
        - id   : 11000
          title: Třmenové řemeny klasické
          slug : trmenove-remeny-klasicke
        - id   : 11001
          title: Třmenové řemeny jednořemenné
          slug : trmenove-remeny-jednoremenne

    - id    : 12
      title : Uzdečky a bezudidlovky
      slug  : uzdecky-a-bezudidlovky
      products :
        - id   : 12000
          title: Bezudidlová uzdečka
          slug : bezudidlova-uzdecka
        - id   : 12001
          title: Bezudidlová uzdečka Bitless Bridle
          slug : bezudidlova-uzdecka-bitless-bridle
        - id   : 12002
          title: Bezudidlová uzdečka Sidepull
          slug : bezudidlova-uzdecka-sidepull
        - id   : 12003
          title: Uzdečka anglická
          slug : uzdecka-anglicka
        - id   : 12004
          title: Uzdečka bez nánosníku
          slug : uzdecka-bez-nanosniku
        - id   : 12005
          title: Uzdečka dvouuška
          slug : uzdecka-dvouuska
        - id   : 12006
          title: Uzdečka jednouška
          slug : uzdecka-jednouska
        - id   : 12007
          title: Uzdečka jednořemínková
          slug : uzdecka-jednoreminkova
        - id   : 12008
          title: Uzdečka s Hackamore
          slug : uzdecka-s-hackamore
        - id   : 12009
          title: Uzdečka v kombinaci s ohlávkou
          slug : uzdecka-v-kombinaci-s-ohlavkou
        - id   : 12010
          title: Uzdečka westernová
          slug : uzdecka-westernova

    - id    : 13
      title : Výstavy a předvádění
      slug  : vystavy-a-predvadeni
      products :
        - id   : 13000
          title: Výstavní a předváděcí ohlávky
          slug : vystavni-a-predvadeci-ohlavky
        - id   : 13001
          title: Výstavní a předváděcí uzdečky
          slug : vystavni-a-predvadeci-uzdecky
        - id   : 13002
          title: Výstavní a předváděcí vodítka
          slug : vystavni-a-predvadeci-voditka

- id    : 1
  title : Pejsci a kočičky
  slug  : pejsci-a-kocicky
- id    : 2
  title : Jiná zvířátka
  slug  : jina-zviratka
- id    : 3
  title : Ostatní
  slug  : ostatni
